feat: added new component Card
eakansh125/Fleet-UI pull request #3
Opened 2022-02-09 15:08 UTC by eakansh125

2022-02-09 15:19 UTC, Naman-Saxena1 requested changes
Your Card with badge has badge on icons, badge should be on the card itself.

2022-02-09 15:19 UTC, Naman-Saxena1 commented on card.html
> +                                    <img src="https://img.icons8.com/material/18/000000/menu-2--v1.png" />
img with alt attribute is good practice.

2022-02-09 15:19 UTC, Naman-Saxena1 commented on style.css
> +} */
You can remove commented code if not needed.

2022-02-09 15:25 UTC, swastika0015 commented
You can remove the commented code, the rest looks good.

2022-02-09 15:27 UTC, rahulk31 commented
Hey Eakansh, a small UI suggestion:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/39650528/153232764-7c873940-6829-4323-9fd8-adc093eadd16.png">

You can either make the icons a bit larger or the badges bit small so that both contrasts well in size. You can plan to do so in next iteration, upto you.

2022-02-09 16:05 UTC, veereshbv04 commented on style.css
> +.card-footer{
herat icon looks dull, increase the font-size

2022-02-09 16:07 UTC, veereshbv04 commented on card.html
> +                                        <span>5</span>
decrease the size of badge, it looks good

2022-02-09 17:20 UTC, mehulsatardekar approved these changes

2022-02-09 17:20 UTC, mehulsatardekar commented on card.html
> +                                <img src="img/stadium.jpg">
You can add lazy loading on images by adding the **loading="lazy"**  attribute to improve the performance.

2022-02-09 17:20 UTC, mehulsatardekar commented on card.html
> +                                <img src="img/stadium.jpg">
Add lazy loading here too

2022-02-09 17:20 UTC, mehulsatardekar commented on style.css
> +.card-lowerRight>img{
try avoiding CSS combinators as much as possible it may create problems later on, suppose you want to make some images small and some big so another styling won't work here. instead, use CSS classes.

2022-02-09 17:22 UTC, mehulsatardekar commented on style.css
> +.card-lowerRight>img{
After the changes good to merge from my side.

2022-02-12 06:36 UTC, eakansh125 commented
Resolved:
1. Removed commented code
2. Added badge on the card instead of badge on icons
3. Added alt attribute to images
4. Planning to avoid combinators going forward

2022-02-12 06:38 UTC, merged